import re

def edit_index(index_input_path, index_output_path=None):
    
    if index_output_path is None:
        index_output_path = index_input_path
        
    f = open(index_input_path, 'r', encoding="utf-8")
    data_docs = f.read()
    f.close()


    text="""<div class="col-lg-2 col-md-2 col-sm-12 d-sm-block px-0">
  <div class="mb-4">
  
    <div class="col-12 p-0">
      <p>
        Data Docs autogenerated using
        <a href="https://greatexpectations.io/">Great Expectations</a>.
      </p>
    </div>
  
</div>
  <div class="sticky">
    
      <script>
    function showAllValidations() {
    $(".hide-succeeded-validation-target-child").parent().fadeIn();
    $(".hide-succeeded-validation-target").fadeIn();
    $(".hide-succeeded-validations-column-section-target-child").parent().parent().each((idx, el) => {
      $(el).fadeIn();
      const elId = el.id;
      $(`a[href$=${elId}]`).fadeIn();
    })
  }

    function hideSucceededValidations() {
    $(".hide-succeeded-validation-target-child").parent().fadeOut();
    $(".hide-succeeded-validation-target").fadeOut();
    $(".hide-succeeded-validations-column-section-target-child").parent().parent().each((idx, el) => {
      $(el).fadeOut();
      const elId = el.id;
      $(`a[href$=${elId}]`).fadeOut();
    })
  }
</script>

<div class="card mb-3">
  <div class="card-header p-2">
    <strong>Actions</strong>
  </div>
  <div class="card-body p-3">
    
    
      

      <div class="mb-2">
        <div class="d-flex justify-content-center">
          <button type="button" class="btn btn-info" data-toggle="modal" data-target=".ge-walkthrough-modal">
            Show Walkthrough
          </button>
        </div>
      </div>
    
  </div>
</div>
    
    
  </div>
</div>"""
    data_docs = data_docs.replace(text, '')
    
    data_docs = data_docs.replace('<div class="col-lg-2 col-md-2 col-sm-12 d-sm-block px-0">', '<div class="col-lg-2 col-md-2 col-sm-12 d-sm-block px-0" style="visibility: hidden;">')
    data_docs = data_docs.replace('<div class="col-md-10 col-lg-10 col-xs-12 pl-md-4 pr-md-3">', '<div class="col-md-12 col-lg-12 col-xs-12 pl-md-4 pr-md-3">')

    # Traduções
    data_docs = data_docs.replace('Data Docs', 'Relatórios gerenciais')
    data_docs = data_docs.replace('local_site', 'Curadoria de dados')
    data_docs = data_docs.replace('Search', 'Busca')
    data_docs = data_docs.replace('Clear Filters', 'Limpar filtros')
    data_docs = data_docs.replace('rows per page', 'linhas por página')
    data_docs = data_docs.replace('Showing', 'Exibindo')
    data_docs = data_docs.replace(' to ', 'até')
    data_docs = data_docs.replace(' of ', 'de')
    data_docs = data_docs.replace(' rows', 'linhas')
    data_docs = data_docs.replace('Run Time', 'Data da execução')
    data_docs = data_docs.replace('Run Name', 'Versão')
    data_docs = data_docs.replace('Asset Name', 'Tabela')
    data_docs = data_docs.replace('Expectation Suites', 'Indicadores executados')
    data_docs = data_docs.replace('Expectation Suite', 'Indicadores executados')
    data_docs = data_docs.replace('Validation Results', 'Resultados dos Indicadores')
    



    f = open(index_output_path, 'w', encoding="utf-8")
    f.write(data_docs)
    f.close()
    
    return None